### ISSUE TITLE
Realms search field is case-sensitive, which creates issues.

### ISSUE THREAD

**Issue by pizza4gleb** [TaggrNetwork/Taggr#10]
Pre-conditions:
Create Realm with uppercase name (as an example https://taggr.link/#/realm/ARTHUB)

How to reproduce:

- goto https://taggr.link/#/realms
- pass value arthub in field becaue uppercase in not applicable for this field 

Result:
Nothing was found 
![IMG_5836](https://github.com/TaggrNetwork/Taggr/assets/47334912/27956c05-3f1b-4d77-abe4-32fecb890566)

Expected result:
https://taggr.link/#/realm/ARTHUB Is presented in results

**Comment by taggrx** [comment]
Thanks! Will be fixed in the next release.

**Comment by pizza4gleb** [comment]
Could I potentially receive compensation for these minor bugs?
