### ISSUE TITLE
guide to deploy locally Taggr

### ISSUE THREAD

**Issue by peterpeterparker** [TaggrNetwork/taggr#134]
I did not knew how to start locally Taggr. So I just started `npm run start` because I was interested by the frontend but, it failed because there was no local dfx. So I started `dfx start` and did a `dfx deploy` but, it ended in error.

Did not block me to provide a static PR but, might be interesting to provide the few command lines that should be executed to develop locally this repo.

**Comment by nathanosdev** [comment]
<img width="601" alt="image" src="https://github.com/TaggrNetwork/taggr/assets/12646525/abb0a36b-2657-4de2-82a8-10b202ecf4ec">

This is at the bottom of the readme, you can find everything you need to know here: https://github.com/TaggrNetwork/taggr/blob/main/docs/LOCAL_DEVELOPMENT.md

Do you think it's not clear enough? Or was this just an oversight on your side?

**Comment by peterpeterparker** [comment]
@nathanosdev I went through the README quickly so with a "Contributing" title I guess I excepted a section about contributing guidelines like what are the requirements to provide a PR, what things to test etc. and not the information about running it locally. Now I know, thanks for the answer.

**Comment by nathanosdev** [comment]
Ah I see, that makes sense. Thanks for the feedback, I've opened a PR to hopefully make the readme clearer for future developers: https://github.com/TaggrNetwork/taggr/pull/136

**Comment by peterpeterparker** [comment]
Cool 👍
