### ISSUE TITLE
 Improve exploration of TXs

### ISSUE THREAD

**Issue by mechaquan** [TaggrNetwork/taggr#19]
I think it would be great to be able to see all holders on the token page

https://share.taggr.link/tokens

**Comment by taggrx** [comment]
To do what? This won't scale if we have thousands of them right? Maybe what you want is showing principals on profiles?

**Comment by mechaquan** [comment]
I suppose a search would do as well.

Just thought expanding to more than 25 would be good! Maybe 50?  100?

**Comment by taggrx** [comment]
The search is already available, even by the user name.

**Comment by taggrx** [comment]
Add pages for transactions with detailed info
