### ISSUE TITLE
Post deletion

### ISSUE THREAD

**Issue by taggrx** [TaggrNetwork/taggr#9]
Let a user delete their post, but preserve the hash for provability.

**Comment by radu-daniel** [comment]
Does this mean we are going to allow post deletion?

**Comment by taggrx** [comment]
Oh no, I actually wouldn't just go and implement this feature. We definitely need to revive the discussions first, but some people brought up really good arguments that are hard to dismiss, see this post: https://taggr.top/#/post/10945

**Comment by radu-daniel** [comment]
I see, yes something worth debating in taggrdao
